import lz4 compression algorithm.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -188,6 +188,19 @@ if [ -z "$ENABLE_SHARED_MONGOC" ]; then
   echo "OK"
 fi
 
+# compile LZ4
+cd "$BASEDIR/3rdparty/lz4-1.8.3"
+echo
+echo -n "Compiling LZ4 ... "
+make clean >/dev/null 2>&1
+make >/dev/null 2>&1
+RET=$?
+if [ $RET != 0 ]; then
+  echo "failed"
+  echo "LZ4 not available."
+  exit $RET
+fi
+
 echo
 echo "First, run \"make\" and \"sudo make install\" in src directory."
 echo "Next, run \"make\" and \"sudo make install\" in tools directory."
