updated version strings.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -170,19 +170,21 @@ $QMAKE -recursive $OPT target.path=\"$BINDIR\" header.path=\"$INCLUDEDIR\" datad
 make qmake
 
 # compile MongoDB files
-cd "$BASEDIR/3rdparty/mongo-c-driver"
-echo
-echo -n "Compiling MongoDB driver library ... "
-$QMAKE $OPT mongo-c-driver.pro
-make clean >/dev/null 2>&1
-make >/dev/null 2>&1
-RET=$?
-if [ $RET != 0 ]; then
-  echo "failed"
-  echo "MongoDB driver not available."
-  exit $RET
+if [ -z "$ENABLE_SHARED_MONGOC" ]; then
+  cd "$BASEDIR/3rdparty/mongo-c-driver"
+  echo
+  echo -n "Compiling MongoDB driver library ... "
+  $QMAKE $OPT mongo-c-driver.pro
+  make clean >/dev/null 2>&1
+  make >/dev/null 2>&1
+  RET=$?
+  if [ $RET != 0 ]; then
+    echo "failed"
+    echo "MongoDB driver not available."
+    exit $RET
+  fi
+  echo "OK"
 fi
-echo "OK"
 
 echo
 echo "First, run \"make\" and \"sudo make install\" in src directory."
