fix compilation error on GitHub actions.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -175,10 +175,20 @@ cd "$BASEDIR/src"
 rm -f .qmake.stash
 [ -f Makefile ] && make -k distclean >/dev/null 2>&1
 $QMAKE $OPT target.path=\"$LIBDIR\" header.path=\"$INCLUDEDIR\" $ENABLE_GUI $ENABLE_SHARED_MONGOC
+RET=$?
+if [ $RET != 0 ]; then
+  echo "qmake failed"
+  exit $RET
+fi
 cd "$BASEDIR/tools"
 rm -f .qmake.stash
 [ -f Makefile ] && make -k distclean >/dev/null 2>&1
 $QMAKE -recursive $OPT target.path=\"$BINDIR\" header.path=\"$INCLUDEDIR\" datadir=\"$DATADIR\" lib.path=\"$LIBDIR\"
+RET=$?
+if [ $RET != 0 ]; then
+  echo "qmake failed"
+  exit $RET
+fi
 make qmake
 
 # compile MongoDB files
