update condifure.bat

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -154,9 +154,9 @@ fi
 
 # search qmake command
 if [ -z "$QMAKE" ]; then
+  which qmake     >/dev/null 2>&1 && QMAKE=qmake
   which qmake-qt5 >/dev/null 2>&1 && QMAKE=qmake-qt5
   which qmake6    >/dev/null 2>&1 && QMAKE=qmake6
-  [ -z "$QMAKE" ] && which qmake >/dev/null 2>&1 && QMAKE=qmake
 
   if [ -z "$QMAKE" ]; then
     echo "qmake: command not found"
@@ -165,8 +165,14 @@ if [ -z "$QMAKE" ]; then
   fi
 fi
 
-if [ -z "$ENABLE_SHARED_MONGOC" ] && ! which cmake >/dev/null 2>&1; then
+if ! which cmake >/dev/null 2>&1; then
   echo "cmake: command not found"
+  echo
+  exit 1
+fi
+
+if [ -n "$ENABLE_SHARED_MONGOC" ] && ! which pkg-config >/dev/null 2>&1; then
+  echo "pkg-config: command not found"
   echo
   exit 1
 fi
