updated configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -59,6 +59,7 @@ BINDIR=$PREFIX/bin
 LIBDIR=$PREFIX/lib
 INCLUDEDIR=$PREFIX/include/treefrog
 DATADIR=$PREFIX/share/treefrog
+CMAKE=cmake
 
 # parse options
 while [ -n "`echo $1 | grep '-'`" ]; do
@@ -140,6 +141,9 @@ if [ "$KERNEL" = "Darwin" ]; then  # macOS
 else
   if [[ "$SPEC" =~ "wasm" ]]; then
     OPT=
+    CMAKE="emcmake cmake"
+    CC=emcc
+    AR=emar
   elif [ "$MACHINE" = "x86_64" ]; then
     OPT="$OPT CONFIG+=x86_64"
   fi
@@ -217,7 +221,7 @@ if [ -z "$ENABLE_SHARED_MONGOC" ]; then
   find . -type f | grep CMakeCache | xargs rm -f
   find . -type f | grep Makefile | xargs rm -f
   find . -type f | grep cmake_install | xargs rm -f
-  cmake -S . -DCMAKE_BUILD_TYPE=Release -DENABLE_STATIC=ON -DENABLE_SSL=OFF -DENABLE_SNAPPY=OFF -DENABLE_ZLIB=OFF -DENABLE_ZSTD=OFF -DENABLE_SRV=OFF -DENABLE_SASL=OFF -DENABLE_SHM_COUNTERS=OFF -DENABLE_TESTS=OFF >/dev/null 2>&1
+  $CMAKE -S . -DCMAKE_BUILD_TYPE=Release -DENABLE_STATIC=ON -DENABLE_SSL=OFF -DENABLE_SNAPPY=OFF -DENABLE_ZLIB=OFF -DENABLE_ZSTD=OFF -DENABLE_SRV=OFF -DENABLE_SASL=OFF -DENABLE_SHM_COUNTERS=OFF -DENABLE_TESTS=OFF >/dev/null 2>&1
   make clean >/dev/null 2>&1
   make -j${NPROC} mongoc_static >/dev/null 2>&1
   RET=$?
@@ -230,21 +234,23 @@ if [ -z "$ENABLE_SHARED_MONGOC" ]; then
 fi
 
 # compile glog
-cd "$BASEDIR/3rdparty/glog"
-rm -rf build
-if [ -z "$ENABLE_SHARED_GLOG" ]; then
-  echo
-  echo -n "Compiling glog ... "
-  cmake -S . -B build -G "Unix Makefiles" >/dev/null 2>&1
-  make -j${NPROC} -C build >/dev/null 2>&1
-  RET=$?
-  if [ $RET != 0 ]; then
-    make -C build
-    echo "failed"
-    echo "glog not available."
-    exit $RET
+if ! [[ "$SPEC" =~ "wasm" ]]; then
+  cd "$BASEDIR/3rdparty/glog"
+  rm -rf build
+  if [ -z "$ENABLE_SHARED_GLOG" ]; then
+    echo
+    echo -n "Compiling glog ... "
+    $CMAKE -S . -B build -G "Unix Makefiles" >/dev/null 2>&1
+    make -j${NPROC} -C build >/dev/null 2>&1
+    RET=$?
+    if [ $RET != 0 ]; then
+      make -C build
+      echo "failed"
+      echo "glog not available."
+      exit $RET
+    fi
+    echo "OK"
   fi
-  echo "OK"
 fi
 
 # compile LZ4
